### ISSUE TITLE
Hashes in extconfig

### ISSUE THREAD

**Issue by mat1010** [oxc/puppet-dovecot#19]
Is there a way adding hashes into an `extconfig`? Most of my extconfigs follow the rules of the module and it works great so far. But I have one extconfig, for acls that are saved in the database, that would require a hash.

The final extconfig should look like this:
```
connect = host=127.0.0.1 dbname=mail user=username password=password
map {
  pattern = shared/shared-boxes/user/$to/$from
  table = user_shares
  value_field = dummy
  fields {
    from_user = $from
    to_user = $to
  }
}
map {
  pattern = shared/shared-boxes/anyone/$from
  table = anyone_shares
  value_field = dummy

  fields {
    from_user = $from
  }
}
```
The extconfigs resource I tried it with looks like this
```
dovecot::extconfigs:
  'dovecot-dict-sql.conf.ext':
    connect: "host=127.0.0.1 dbname=mail user=imap%{serverid} password=%{lookup('imap_mysql_password')}"
    map:
      pattern: shared/shared-boxes/user/$to/$from
      table: user_shares
      value_field: dummy
      fields:
        from_user: $from
        to_user: $to
    map:
      pattern: shared/shared-boxes/anyone/$from
      table: anyone_shares
      value_field: dummy
      fields:
        from_user: $from
```

Right now this fails, since only strings are allowed in the key: value mappings. Is there a way arround it?

Thanks in advance
