### ISSUE TITLE
dovecot::extconfigs just printing additional_content

### ISSUE THREAD

**Issue by SimonHoenscheid** [oxc/puppet-dovecot#26]
I am currently using the module to set up a dovecot server. I am trying to fill the file `auth-sql.conf.ext` with the following content:

```
passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}
userdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}
```
Declaring it in Hiera like this: 
```
dovecot::extconfigs:
  'auth-sql.conf.ext':
    additional_content: |+
      passdb {
        driver = sql
        args = /etc/dovecot/dovecot-sql.conf.ext
      }
      userdb {
        driver = sql
        args = /etc/dovecot/dovecot-sql.conf.ext
      }
```

ends up with content like this:
```
additional_content = passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}
userdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}
```

Whats the correct way to solve this?

**Comment by oxc** [comment]
If I remember correctly, it should work like this:
```
dovecot::extconfigs:
  'auth-sql.conf.ext':
    passdb:
      driver: sql
      args: /etc/dovecot/dovecot-sql.conf.ext
    userdb:
      driver: sql
      args: /etc/dovecot/dovecot-sql.conf.ext
```
